[target.x86_64-pc-windows-msvc]
linker = "lld"
rustflags = [
  "-Lnative=/Users/kianheitkamp/.xwin/crt/lib/x86_64",
  "-Lnative=/Users/kianheitkamp/.xwin/sdk/lib/um/x86_64",
  "-Lnative=/Users/kianheitkamp/.xwin/sdk/lib/ucrt/x86_64"
]