[package]
name = "automail"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
colored = "2.1.0"
inquire = "0.6.2"
lettre = "0.11.4"
rpassword = "7.3.1"
toml = "0.8.10"
